version: "3.1"

services:
  postgres_checkout:
    image: postgres:15.1
    environment:
      POSTGRES_DB: checkout
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: 'postgres-container-checkout'
    volumes:
      - .:/var/lib/postgresql/checkout/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d checkout" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  postgres_loms:
    image: postgres:15.1
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: 'postgres-container-loms'
    volumes:
      - .:/var/lib/postgresql/loms/data
    ports:
      - 5433:5433
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d loms" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    command: -p 5433

  checkout:
    image: checkout
    build: ./checkout/
    ports:
      - "8080:8080"

  loms:
    image: loms
    build: ./loms/
    ports:
      - "8081:8081"


  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
